// Code generated by Kitex v0.12.2. DO NOT EDIT.

package fabricipfs

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	fabric_ipfs "github.com/wxl-server/idl_gen/kitex_gen/fabric_ipfs"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateCreateEblDocxDocx": kitex.NewMethodInfo(
		createCreateEblDocxDocxHandler,
		newFabricIpfsCreateCreateEblDocxDocxArgs,
		newFabricIpfsCreateCreateEblDocxDocxResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	fabricIpfsServiceInfo                = NewServiceInfo()
	fabricIpfsServiceInfoForClient       = NewServiceInfoForClient()
	fabricIpfsServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return fabricIpfsServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return fabricIpfsServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return fabricIpfsServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "FabricIpfs"
	handlerType := (*fabric_ipfs.FabricIpfs)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "fabric_ipfs",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.2",
		Extra:           extra,
	}
	return svcInfo
}

func createCreateEblDocxDocxHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*fabric_ipfs.FabricIpfsCreateCreateEblDocxDocxArgs)
	realResult := result.(*fabric_ipfs.FabricIpfsCreateCreateEblDocxDocxResult)
	success, err := handler.(fabric_ipfs.FabricIpfs).CreateCreateEblDocxDocx(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFabricIpfsCreateCreateEblDocxDocxArgs() interface{} {
	return fabric_ipfs.NewFabricIpfsCreateCreateEblDocxDocxArgs()
}

func newFabricIpfsCreateCreateEblDocxDocxResult() interface{} {
	return fabric_ipfs.NewFabricIpfsCreateCreateEblDocxDocxResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateCreateEblDocxDocx(ctx context.Context, req *fabric_ipfs.CreateCreateEblDocxDocxReq) (r *fabric_ipfs.CreateCreateEblDocxDocxResp, err error) {
	var _args fabric_ipfs.FabricIpfsCreateCreateEblDocxDocxArgs
	_args.Req = req
	var _result fabric_ipfs.FabricIpfsCreateCreateEblDocxDocxResult
	if err = p.c.Call(ctx, "CreateCreateEblDocxDocx", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
