// Code generated by Kitex v0.12.3. DO NOT EDIT.
package minerintegrate

import (
	server "github.com/cloudwego/kitex/server"
	miner_integrate "github.com/wxl-server/idl_gen/kitex_gen/miner_integrate"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler miner_integrate.MinerIntegrate, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler miner_integrate.MinerIntegrate, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
