// Code generated by Kitex v0.12.2. DO NOT EDIT.

package fabriccreateebldocx

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	fabric_ebl "github.com/wxl-server/idl_gen/kitex_gen/fabric_ebl"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateCreateEblDocxDocx": kitex.NewMethodInfo(
		createCreateEblDocxDocxHandler,
		newFabricCreateEblDocxCreateCreateEblDocxDocxArgs,
		newFabricCreateEblDocxCreateCreateEblDocxDocxResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	fabricCreateEblDocxServiceInfo                = NewServiceInfo()
	fabricCreateEblDocxServiceInfoForClient       = NewServiceInfoForClient()
	fabricCreateEblDocxServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return fabricCreateEblDocxServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return fabricCreateEblDocxServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return fabricCreateEblDocxServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "FabricCreateEblDocx"
	handlerType := (*fabric_ebl.FabricCreateEblDocx)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "fabric_ebl",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.2",
		Extra:           extra,
	}
	return svcInfo
}

func createCreateEblDocxDocxHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*fabric_ebl.FabricCreateEblDocxCreateCreateEblDocxDocxArgs)
	realResult := result.(*fabric_ebl.FabricCreateEblDocxCreateCreateEblDocxDocxResult)
	success, err := handler.(fabric_ebl.FabricCreateEblDocx).CreateCreateEblDocxDocx(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFabricCreateEblDocxCreateCreateEblDocxDocxArgs() interface{} {
	return fabric_ebl.NewFabricCreateEblDocxCreateCreateEblDocxDocxArgs()
}

func newFabricCreateEblDocxCreateCreateEblDocxDocxResult() interface{} {
	return fabric_ebl.NewFabricCreateEblDocxCreateCreateEblDocxDocxResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateCreateEblDocxDocx(ctx context.Context, req *fabric_ebl.CreateCreateEblDocxDocxReq) (r *fabric_ebl.CreateCreateEblDocxDocxResp, err error) {
	var _args fabric_ebl.FabricCreateEblDocxCreateCreateEblDocxDocxArgs
	_args.Req = req
	var _result fabric_ebl.FabricCreateEblDocxCreateCreateEblDocxDocxResult
	if err = p.c.Call(ctx, "CreateCreateEblDocxDocx", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
